"""
Write .streamlit/secrets.toml from a Google service-account JSON key.

    python make_secrets.py path\\to\\key.json

Keeps the dashboard settings, converts every key-file field to valid TOML, and
backs up any existing secrets.toml first.
"""
from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

SETTINGS = {
    "GCP_PROJECT": "aerobic-copilot-494105-b6",
    "BQ_DATASET": "Datachannel",
    "BQ_TABLE": "Executive_Sales_Master",
    "BQ_WEEKLY_TABLE": "Executive_Weekly_Gross_Sales",
    "BQ_AD_TABLE": "Executive_Spends_Master",
    "BQ_TARGET_TABLE": "AOP_Daily_Target_vs_Achievement",
    "BQ_AOP_TABLE": "AOP_targets",
}


def _toml_str(value) -> str:
    # json.dumps gives a valid TOML basic string: quotes, backslashes and newlines escaped
    return json.dumps(value) if isinstance(value, str) else json.dumps(str(value))


def main(key_path: str) -> None:
    key = json.loads(Path(key_path).read_text(encoding="utf-8"))
    if key.get("type") != "service_account" or "private_key" not in key:
        sys.exit("That file doesn't look like a service-account JSON key.")

    lines = ["# Generated by make_secrets.py. Never commit this file.", ""]
    lines += [f"{k} = {_toml_str(v)}" for k, v in SETTINGS.items()]
    lines += ["", "[gcp_service_account]"]
    lines += [f"{k} = {_toml_str(v)}" for k, v in key.items()]

    out = Path(__file__).resolve().parent / ".streamlit" / "secrets.toml"
    out.parent.mkdir(exist_ok=True)
    if out.exists():
        shutil.copy(out, out.with_suffix(".toml.bak"))
        print(f"Backed up the old file to {out.with_suffix('.toml.bak').name}")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    import tomllib
    tomllib.loads(out.read_text(encoding="utf-8"))  # fails loudly if anything is off
    print(f"Wrote {out} for {key.get('client_email')}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit("Usage: python make_secrets.py path\\to\\key.json")
    main(sys.argv[1])
